import "dotenv/config";
import { getPrismaClient } from "../src/lib/prisma";

const prisma = getPrismaClient();

const events = [
  // ── EVENTS from OSU_API ──────────────────────────────────────────
  {
    title: "Spring Career Fair 2026",
    description: "Connect with over 200 employers from Fortune 500 companies and innovative startups. Bring your resume and dress professionally. Open to all majors and graduation years.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-career-fair-spring-2026",
    category: "career",
    tags: ["career", "networking", "jobs", "internships"],
    locationName: "Ohio Union Archie M. Griffin Grand Ballroom",
    locationLatitude: 39.9976,
    locationLongitude: -83.0087,
    startAt: new Date("2026-03-20T10:00:00-04:00"),
    endAt: new Date("2026-03-20T16:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "OSU Symphony Orchestra: Spring Concert",
    description: "The Ohio State University Symphony Orchestra presents an evening of Tchaikovsky and Rachmaninoff. Featuring piano soloist Dr. Elena Martínez performing Piano Concerto No. 2.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-symphony-spring-2026",
    category: "arts",
    tags: ["music", "orchestra", "classical", "performance"],
    locationName: "Weigel Auditorium",
    locationLatitude: 40.0009,
    locationLongitude: -83.0095,
    startAt: new Date("2026-03-22T19:30:00-04:00"),
    endAt: new Date("2026-03-22T21:30:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Buckeye Bash Block Party",
    description: "Annual spring block party on the Oval featuring food trucks, live DJs, student org booths, and free giveaways. Celebrate the end of midterms with the entire Buckeye community!",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-buckeye-bash-2026",
    category: "social",
    tags: ["party", "social", "food", "music", "outdoor"],
    locationName: "The Oval",
    locationLatitude: 39.9995,
    locationLongitude: -83.0107,
    startAt: new Date("2026-04-04T12:00:00-04:00"),
    endAt: new Date("2026-04-04T22:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Guest Lecture: AI Ethics in Healthcare",
    description: "Dr. Fei-Fei Li from Stanford discusses the ethical implications of deploying AI systems in clinical settings. Q&A session to follow. Open to all students and faculty.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-ai-ethics-lecture-2026",
    category: "academic",
    tags: ["AI", "ethics", "healthcare", "lecture", "technology"],
    locationName: "Knowlton Hall Auditorium",
    locationLatitude: 40.0023,
    locationLongitude: -83.0156,
    startAt: new Date("2026-03-25T14:00:00-04:00"),
    endAt: new Date("2026-03-25T15:30:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Intramural Soccer Tournament Finals",
    description: "Watch the top intramural soccer teams battle it out for the spring championship. Free admission with BuckID. Concessions available.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-im-soccer-finals-2026",
    category: "sports",
    tags: ["soccer", "intramural", "sports", "tournament"],
    locationName: "Jesse Owens Memorial Stadium",
    locationLatitude: 40.0068,
    locationLongitude: -83.0197,
    startAt: new Date("2026-04-12T14:00:00-04:00"),
    endAt: new Date("2026-04-12T18:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Hackathon: HackOHI/O 2026",
    description: "Ohio State's flagship hackathon returns! 36 hours of building, workshops, and mentorship. $10,000+ in prizes. All skill levels welcome — form teams of up to 4.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-hackohio-2026",
    category: "technology",
    tags: ["hackathon", "coding", "technology", "prizes", "teamwork"],
    locationName: "Ohio Union",
    locationLatitude: 39.9976,
    locationLongitude: -83.0087,
    startAt: new Date("2026-04-18T18:00:00-04:00"),
    endAt: new Date("2026-04-20T06:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Study Abroad Info Session: Europe",
    description: "Learn about OSU's study abroad programs in London, Berlin, Paris, and Barcelona. Hear from students who studied abroad last year. Financial aid and scholarship info provided.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-study-abroad-europe-2026",
    category: "academic",
    tags: ["study abroad", "travel", "Europe", "academic"],
    locationName: "Enarson Hall Room 200",
    locationLatitude: 39.9982,
    locationLongitude: -83.0116,
    startAt: new Date("2026-03-27T16:00:00-04:00"),
    endAt: new Date("2026-03-27T17:30:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "OSU Farmer's Market",
    description: "Weekly farmer's market featuring local produce, baked goods, honey, and handmade crafts from central Ohio vendors. Student org fundraiser booths welcome.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-farmers-market-mar-2026",
    category: "community",
    tags: ["food", "local", "market", "community", "outdoor"],
    locationName: "South Oval",
    locationLatitude: 39.9985,
    locationLongitude: -83.0119,
    startAt: new Date("2026-03-28T09:00:00-04:00"),
    endAt: new Date("2026-03-28T13:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Mental Health Awareness Workshop",
    description: "Interactive workshop covering stress management, mindfulness techniques, and campus mental health resources. Led by OSU Counseling and Consultation Service staff.",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-mental-health-workshop-2026",
    category: "wellness",
    tags: ["mental health", "wellness", "workshop", "self-care"],
    locationName: "Ohio Union Cartoon Room",
    locationLatitude: 39.9976,
    locationLongitude: -83.0087,
    startAt: new Date("2026-04-02T13:00:00-04:00"),
    endAt: new Date("2026-04-02T14:30:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "OSU Dance Marathon",
    description: "12-hour dance marathon raising money for Nationwide Children's Hospital. Registration fee includes t-shirt and meals. Last year raised over $1.5M!",
    type: "EVENT" as const,
    source: "OSU_API" as const,
    externalId: "osu-dance-marathon-2026",
    category: "philanthropy",
    tags: ["dance", "charity", "fundraiser", "community"],
    locationName: "Recreation and Physical Activity Center (RPAC)",
    locationLatitude: 40.0042,
    locationLongitude: -83.0181,
    startAt: new Date("2026-04-05T10:00:00-04:00"),
    endAt: new Date("2026-04-05T22:00:00-04:00"),
    status: "OPEN" as const,
  },

  // ── EVENTS from TICKETMASTER ─────────────────────────────────────
  {
    title: "Olivia Rodrigo — GUTS World Tour",
    description: "Olivia Rodrigo brings her GUTS World Tour to Columbus! General admission floor and reserved seating available. Doors open at 6:30 PM.",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-olivia-rodrigo-cbus-2026",
    category: "concert",
    tags: ["concert", "pop", "music", "live"],
    imageUrl: "https://example.com/olivia-rodrigo-tour.jpg",
    ticketUrl: "https://www.ticketmaster.com/event/olivia-rodrigo-columbus",
    locationName: "Nationwide Arena",
    locationLatitude: 39.9692,
    locationLongitude: -83.006,
    startAt: new Date("2026-04-10T19:00:00-04:00"),
    endAt: new Date("2026-04-10T23:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Columbus Blue Jackets vs. Pittsburgh Penguins",
    description: "NHL regular season game. Blue Jackets take on division rivals the Pittsburgh Penguins. Student discount available with valid .edu email.",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-cbj-pit-apr-2026",
    category: "sports",
    tags: ["hockey", "NHL", "Blue Jackets", "sports"],
    imageUrl: "https://example.com/cbj-penguins.jpg",
    ticketUrl: "https://www.ticketmaster.com/event/cbj-penguins-apr",
    locationName: "Nationwide Arena",
    locationLatitude: 39.9692,
    locationLongitude: -83.006,
    startAt: new Date("2026-04-08T19:00:00-04:00"),
    endAt: new Date("2026-04-08T22:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Columbus Crew vs. FC Cincinnati",
    description: "MLS Hell is Real Derby! Watch the Crew take on in-state rivals FC Cincinnati at Lower.com Field. Tailgate starts at 4 PM in the Nordecke lot.",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-crew-fcc-2026",
    category: "sports",
    tags: ["soccer", "MLS", "Crew", "sports", "derby"],
    ticketUrl: "https://www.ticketmaster.com/event/crew-fcc-2026",
    locationName: "Lower.com Field",
    locationLatitude: 39.9689,
    locationLongitude: -83.017,
    startAt: new Date("2026-04-15T19:30:00-04:00"),
    endAt: new Date("2026-04-15T21:30:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Stand-Up Comedy Night: John Mulaney",
    description: "John Mulaney performs his latest material at the Palace Theatre. Two shows: 7 PM and 10 PM. Ages 18+.",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-mulaney-cbus-2026",
    category: "comedy",
    tags: ["comedy", "stand-up", "live", "entertainment"],
    ticketUrl: "https://www.ticketmaster.com/event/mulaney-columbus",
    locationName: "Palace Theatre",
    locationLatitude: 39.9604,
    locationLongitude: -82.9988,
    startAt: new Date("2026-04-22T19:00:00-04:00"),
    endAt: new Date("2026-04-22T21:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Columbus Food Truck Festival",
    description: "Over 50 food trucks from across Ohio converge on the Columbus Commons. Live music on two stages. Free admission, pay-as-you-eat.",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-food-truck-fest-2026",
    category: "food",
    tags: ["food", "festival", "outdoor", "music", "Columbus"],
    locationName: "Columbus Commons",
    locationLatitude: 39.9584,
    locationLongitude: -82.9985,
    startAt: new Date("2026-04-25T11:00:00-04:00"),
    endAt: new Date("2026-04-25T21:00:00-04:00"),
    status: "OPEN" as const,
  },

  {
    title: "Indie Film Screening: Columbus Shorts Fest",
    description: "A curated collection of short films by independent filmmakers from the Midwest. Post-screening panel discussion with directors. Free popcorn!",
    type: "EVENT" as const,
    source: "TICKETMASTER" as const,
    externalId: "tm-indie-shorts-fest-2026",
    category: "arts",
    tags: ["film", "indie", "screening", "arts", "entertainment"],
    ticketUrl: "https://www.ticketmaster.com/event/columbus-shorts-fest",
    locationName: "Gateway Film Center",
    locationLatitude: 39.9955,
    locationLongitude: -83.0057,
    startAt: new Date("2026-04-19T18:00:00-04:00"),
    endAt: new Date("2026-04-19T21:00:00-04:00"),
    status: "OPEN" as const,
  },

  // ── USER-CREATED EVENTS ──────────────────────────────────────────
  {
    title: "CS Study Group — Algorithms Final Review",
    description: "Group study session for CSE 2331 (Algorithms) final exam. We'll work through past exams and practice problems together. Bring your notes!",
    type: "EVENT" as const,
    source: "USER" as const,
    category: "academic",
    tags: ["study group", "computer science", "algorithms", "exam prep"],
    locationName: "Thompson Library Room 210",
    locationLatitude: 39.9989,
    locationLongitude: -83.0148,
    startAt: new Date("2026-04-20T18:00:00-04:00"),
    endAt: new Date("2026-04-20T21:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Pickup Basketball — RPAC Courts",
    description: "Informal pickup basketball every Wednesday evening. All skill levels welcome. Just show up with your BuckID. We usually run 5v5 full court.",
    type: "EVENT" as const,
    source: "USER" as const,
    category: "sports",
    tags: ["basketball", "sports", "pickup", "recreation"],
    locationName: "RPAC Basketball Courts",
    locationLatitude: 40.0042,
    locationLongitude: -83.0181,
    startAt: new Date("2026-03-25T19:00:00-04:00"),
    endAt: new Date("2026-03-25T21:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Board Game Night at Gateway",
    description: "Weekly board game night! We have Catan, Ticket to Ride, Codenames, Wingspan, and more. Snacks provided. Bring your own games too!",
    type: "EVENT" as const,
    source: "USER" as const,
    category: "social",
    tags: ["board games", "social", "games", "fun"],
    locationName: "Gateway Film Center Lounge",
    locationLatitude: 39.9955,
    locationLongitude: -83.0057,
    startAt: new Date("2026-03-26T19:00:00-04:00"),
    endAt: new Date("2026-03-26T23:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Sunrise Yoga on Mirror Lake",
    description: "Start your morning with a peaceful yoga session by Mirror Lake. Mats provided. All experience levels welcome. Cancelled if raining.",
    type: "EVENT" as const,
    source: "USER" as const,
    category: "wellness",
    tags: ["yoga", "wellness", "outdoor", "morning", "fitness"],
    locationName: "Mirror Lake Lawn",
    locationLatitude: 39.9986,
    locationLongitude: -83.0109,
    startAt: new Date("2026-04-01T07:00:00-04:00"),
    endAt: new Date("2026-04-01T08:00:00-04:00"),
    status: "OPEN" as const,
  },
  {
    title: "Photography Walk: Spring Blooms on Campus",
    description: "Join us for a casual photography walk capturing spring flowers around campus. DSLR, mirrorless, or phone cameras all welcome. We'll share our best shots afterward.",
    type: "EVENT" as const,
    source: "USER" as const,
    category: "arts",
    tags: ["photography", "nature", "campus", "art", "outdoor"],
    locationName: "Chadwick Arboretum",
    locationLatitude: 40.0064,
    locationLongitude: -83.0282,
    startAt: new Date("2026-04-06T10:00:00-04:00"),
    endAt: new Date("2026-04-06T12:00:00-04:00"),
    status: "OPEN" as const,
  },

  // ── GIGS (USER-CREATED) ──────────────────────────────────────────
  {
    title: "Python Tutor Needed — Intro to Data Science",
    description: "Looking for a tutor for CSE 3244 (Intro to Data Science). Need help with pandas, numpy, and scikit-learn basics. Flexible schedule, 2-3 hours per week.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "tutoring",
    tags: ["tutoring", "Python", "data science", "CSE"],
    locationName: "18th Avenue Library",
    locationLatitude: 40.0016,
    locationLongitude: -83.0109,
    startAt: new Date("2026-03-24T10:00:00-04:00"),
    endAt: new Date("2026-05-01T17:00:00-04:00"),
    compensationAmount: 25,
    compensationType: "HOURLY" as const,
    status: "OPEN" as const,
  },
  {
    title: "Graphic Designer for Club Flyers",
    description: "OSU Dance Club needs a graphic designer to create promotional flyers and social media posts for our spring showcase. 5-8 designs total. Must know Figma or Illustrator.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "design",
    tags: ["graphic design", "Figma", "freelance", "creative"],
    locationName: "Remote / Campus",
    startAt: new Date("2026-03-23T09:00:00-04:00"),
    endAt: new Date("2026-04-15T23:59:00-04:00"),
    compensationAmount: 200,
    compensationType: "FIXED" as const,
    status: "OPEN" as const,
  },
  {
    title: "Moving Help — Apartment on Lane Ave",
    description: "Need 2 people to help move furniture from a 2-bedroom apartment to a truck. Should take about 3 hours. Must be able to lift heavy items.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "labor",
    tags: ["moving", "physical", "help", "quick job"],
    locationName: "1500 Lane Ave, Columbus OH",
    locationLatitude: 40.0044,
    locationLongitude: -83.0324,
    startAt: new Date("2026-03-29T09:00:00-04:00"),
    endAt: new Date("2026-03-29T12:00:00-04:00"),
    compensationAmount: 20,
    compensationType: "HOURLY" as const,
    status: "OPEN" as const,
  },
  {
    title: "React Developer for Student Org Website",
    description: "Buckeye Blockchain Club needs a React developer to build our new website. Includes landing page, member directory, and event calendar. GitHub repo already set up.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "technology",
    tags: ["React", "web development", "freelance", "JavaScript"],
    locationName: "Remote",
    startAt: new Date("2026-03-20T09:00:00-04:00"),
    endAt: new Date("2026-04-30T23:59:00-04:00"),
    compensationAmount: 500,
    compensationType: "FIXED" as const,
    status: "OPEN" as const,
  },
  {
    title: "Dog Walker — Clintonville Area",
    description: "Need someone to walk my golden retriever (friendly, 60 lbs) on MWF afternoons around 2 PM. 30-minute walks. Must be comfortable with large dogs.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "pet care",
    tags: ["dog walking", "pets", "part-time", "flexible"],
    locationName: "Clintonville, Columbus OH",
    locationLatitude: 40.0372,
    locationLongitude: -83.0182,
    startAt: new Date("2026-03-24T14:00:00-04:00"),
    endAt: new Date("2026-05-15T15:00:00-04:00"),
    compensationAmount: 15,
    compensationType: "HOURLY" as const,
    status: "OPEN" as const,
  },
  {
    title: "Note-Taker for ECON 2001",
    description: "Looking for a reliable note-taker for Intermediate Microeconomics (ECON 2001, MWF 11:30). Share typed notes within 24 hours of each lecture. ~13 weeks remaining.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "academic",
    tags: ["note-taking", "economics", "academic", "part-time"],
    locationName: "Mendenhall Lab Room 100",
    locationLatitude: 40.0022,
    locationLongitude: -83.0136,
    startAt: new Date("2026-03-23T11:30:00-04:00"),
    endAt: new Date("2026-06-06T12:30:00-04:00"),
    compensationAmount: 15,
    compensationType: "HOURLY" as const,
    status: "OPEN" as const,
  },
  {
    title: "Video Editor — YouTube Channel",
    description: "OSU gaming YouTube channel (15K subs) looking for a video editor. Need someone familiar with Premiere Pro or DaVinci Resolve. 2-3 videos per week, 10-15 min each.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "media",
    tags: ["video editing", "YouTube", "content creation", "freelance"],
    locationName: "Remote",
    startAt: new Date("2026-03-22T09:00:00-04:00"),
    endAt: new Date("2026-06-15T23:59:00-04:00"),
    compensationAmount: 50,
    compensationType: "FIXED" as const,
    status: "OPEN" as const,
  },
  {
    title: "Campus Tour Guide — Admitted Students Day",
    description: "Volunteer to be a campus tour guide for Admitted Students Day! Training provided. Must be enthusiastic about OSU and available for the full day. Lunch and t-shirt included.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "volunteer",
    tags: ["tour guide", "volunteer", "campus", "admissions"],
    locationName: "Ohio Union (Meeting Point)",
    locationLatitude: 39.9976,
    locationLongitude: -83.0087,
    startAt: new Date("2026-04-11T08:00:00-04:00"),
    endAt: new Date("2026-04-11T17:00:00-04:00"),
    compensationAmount: 0,
    compensationType: "FIXED" as const,
    status: "OPEN" as const,
  },
  {
    title: "Math Tutor — Calculus II",
    description: "Struggling with series and integration techniques in MATH 1152. Looking for an experienced tutor for twice-weekly sessions. Must have gotten an A in the course.",
    type: "GIG" as const,
    source: "USER" as const,
    category: "tutoring",
    tags: ["tutoring", "math", "calculus", "STEM"],
    locationName: "Math Tower Tutoring Center",
    locationLatitude: 40.0019,
    locationLongitude: -83.0156,
    startAt: new Date("2026-03-25T10:00:00-04:00"),
    endAt: new Date("2026-04-25T18:00:00-04:00"),
    compensationAmount: 30,
    compensationType: "HOURLY" as const,
    status: "OPEN" as const,
  },
];

async function main() {
  console.log("Seeding 30 events...");

  for (const event of events) {
    const created = await prisma.event.create({ data: event });
    console.log(`  ✓ ${created.type} — ${created.title}`);
  }

  console.log(`\nDone! Seeded ${events.length} events.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
